### ISSUE TITLE
no support for  download resuming while downloading the patchrom 

### ISSUE THREAD

**Issue by ali1997** [FlymeOS/flyme-release#2]
this is really really disappointed .. i m obliged to redownload the patchrom again and again if my connection refused .. please upload it on another server .. i trying to porting and cannot 
thanks

**Comment by DiorgenesS** [comment]
Your problem is easy to solve, read a little before, the solution to your problem is here:
[FlymeOS/manifest](https://github.com/FlymeOS/manifest)

**Comment by ali1997** [comment]
@DiorgenesS  sorry i cannot understanding china language

**Comment by ali1997** [comment]
thanks >> solved
